$(function(){
	$("#type").change(function(){
		$("#class").parent().toggle();
		$("#studentNo").parent().toggle();
		$("#department").parent().toggle();
		$("#className").parent().toggle();
		$("#course1").parent().toggle();
        $("#course2").parent().toggle();
        $("#course3").parent().toggle();
	});
	$.validator.addMethod("studentNo",val=>{
	//val:自动获得文本框中要验证的值
	if(val.trim().length!=0)
		return /^201[123457][12][0123456789]22\d{2}$/.test(val);
	else return true;
	},"学号格式不正确!");
	$("#reg").validate({
		rules:{
			uname:{
				required:true,
				rangelength:[2,8],
				remote:"data/vali.php"
			},
			upwd:{
				required:true,
				rangelength:[6,8]
			},
			studentNo:{
				required:true,
				studentNo:true,
				remote:"data/vali.php"
			},
			department:{
				required:true
			},
			className:{
				required:true
			}
		},
		messages:{
			uname:{
				required:"用户名不能为空!",
				remote:"用户名已被占用!"
			},
			upwd:{required:"密码不能为空!"},
			studentNo:{
				required:"学号不能为空!",
				remote:"该学号已被注册!"
			},
			department:{
				required:"系别不能为空"
			},
			className:{
				required:"班级不能为空"
			}
		}
	});
	$("#btn1").click(function(e){
		e.preventDefault();
		var data=$("form").serialize();
		$.ajax({
			type:"POST",
			url:"data/routes/user/register.php",
			data:data,
			success:function(data){
				alert(data.msg);
				location.href="index.html";
			},
			error:function(){
				alert("网络故障");
			}
		})
	});
});
